"""initial_schema

Revision ID: 2c347ef4cd08
Revises: 
Create Date: 2026-02-25 17:35:42.116286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c347ef4cd08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('stage', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('retry_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_created', 'files', ['created_at'], unique=False)
    op.create_index('idx_files_hash', 'files', ['file_hash'], unique=False)
    op.create_index('idx_files_operator', 'files', ['operator_id'], unique=False)
    op.create_index('idx_files_status', 'files', ['status'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('standard', sa.SmallInteger(), nullable=False),
    sa.Column('loyalty', sa.SmallInteger(), nullable=False),
    sa.Column('kindness', sa.SmallInteger(), nullable=False),
    sa.Column('overall', sa.SmallInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('kindness BETWEEN 0 AND 100', name='ck_analyses_kindness'),
    sa.CheckConstraint('loyalty BETWEEN 0 AND 100', name='ck_analyses_loyalty'),
    sa.CheckConstraint('overall BETWEEN 0 AND 100', name='ck_analyses_overall'),
    sa.CheckConstraint('standard BETWEEN 0 AND 100', name='ck_analyses_standard'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index('idx_analyses_kindness', 'analyses', ['kindness'], unique=False)
    op.create_index('idx_analyses_loyalty', 'analyses', ['loyalty'], unique=False)
    op.create_index('idx_analyses_overall', 'analyses', ['overall'], unique=False)
    op.create_index('idx_analyses_standard', 'analyses', ['standard'], unique=False)
    op.create_table('diarizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('num_speakers', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('word_timestamps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='ru', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcriptions')
    op.drop_table('diarizations')
    op.drop_index('idx_analyses_standard', table_name='analyses')
    op.drop_index('idx_analyses_overall', table_name='analyses')
    op.drop_index('idx_analyses_loyalty', table_name='analyses')
    op.drop_index('idx_analyses_kindness', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('idx_files_status', table_name='files')
    op.drop_index('idx_files_operator', table_name='files')
    op.drop_index('idx_files_hash', table_name='files')
    op.drop_index('idx_files_created', table_name='files')
    op.drop_table('files')
    op.drop_table('operators')
    # ### end Alembic commands ###
