"""add_files_progress

Revision ID: ada2ee2d6132
Revises: 2c347ef4cd08
Create Date: 2026-02-25 17:50:09.728257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada2ee2d6132'
down_revision: Union[str, Sequence[str], None] = '2c347ef4cd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('progress', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'progress')
    # ### end Alembic commands ###
